default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: dev
  host: localhost

development:
  <<: *default
  database: budget_manager_development

test:
  <<: *default
  database: budget_manager_test

production:
  <<: *default
  database: budget_manager_production
  username: budget_manager
  password: <%= ENV['BUDGET_MANAGER_DATABASE_PASSWORD'] %>
